#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Source the .env file
if [ -f test/geg/backend/.env ]; then
    source .env
fi

export DATABASE_URL="postgres://${DB_USER}:${DB_PWD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}"

python << END
import sys
import time

import psycopg

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        psycopg.connect(
            dbname="${DB_DATABASE}",
            user="${DB_USER}",
            password="${DB_PWD}",
            host="${DB_HOST}",
            port="${DB_PORT}",
        )
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

exec "$@"
