#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Source the .env file
export POSTGRES_USER="avnadmin"
export POSTGRES_PASSWORD="AVNS__VNHkGIKChz5fRuFSiq"
export POSTGRES_HOST="pg-e179d8e0-1be3-447c-b362-4cb4f49b9c21-db1251097756-choreo-org.i.aivencloud.com"
export POSTGRES_PORT="23137"
export POSTGRES_DB="defaultdb"

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python << END
import sys
import time

import psycopg

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        psycopg.connect(
            dbname="${POSTGRES_DB}",
            user="${POSTGRES_USER}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

exec "$@"
