version: '3.8'

services: 

    django:
        build: ./dockerfiles/Back-End
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./dockerfiles/Back-End/:/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment: 
            - POSTGRES_PASSWORD = postgres
            - POSTGRES_USER = postgres
            - POSTGRES_DB = postgres
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-app
        volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
        - 80:80
        depends_on:
        - app
    app:
        build:
            context: .
            dockerfile: ./dockerfiles/Front-End/Dockerfile
        container_name: vue-app
        ports:
        - 8080:80



