# Generated by Django 4.2.11 on 2024-04-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meetingId', models.AutoField(primary_key=True, serialize=False)),
                ('meetingEmail', models.CharField(max_length=50)),
                ('meetingName', models.CharField(max_length=50)),
                ('meetingPhone', models.IntegerField()),
                ('meetingDate', models.DateTimeField()),
                ('meetingMode', models.TextField()),
            ],
        ),
    ]
