# Generated by Django 4.2.11 on 2024-05-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(default='timothy@gmail.com', max_length=30)),
                ('FirstName', models.TextField(default='Fren')),
                ('LastName', models.TextField(default='Marlon')),
                ('Phone', models.IntegerField(default='09324142132')),
                ('Company', models.CharField(default='GEG Company', max_length=20)),
                ('Day', models.TextField(default='04/14/24', max_length=20)),
                ('Time', models.TextField(default='10:00AM')),
                ('Mode', models.TextField(default='Online', max_length=20)),
                ('Plan', models.ImageField(default='plan.jpg', upload_to='plan/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('MainImage', models.ImageField(default='frontend/src/assets/se-dummy-images/dummy-pic-4-abt-us.jpeg', upload_to='project/<django.db.models.fields.CharField>_MainImage')),
                ('SubImage', models.ImageField(default='frontend/src/assets/se-dummy-images/dummy-pic-4-abt-us.jpeg', upload_to='project/<django.db.models.fields.CharField>/subimages')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='Service 1', max_length=50)),
                ('Description', models.TextField(default='This is a Service')),
                ('Image', models.ImageField(default='frontend/src/assets/se-dummy-images/dummy-pic-4-abt-us.jpeg', upload_to='service/')),
            ],
        ),
    ]
