# Generated by Django 4.2.11 on 2024-05-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Mode', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
