# Generated by Django 4.2.11 on 2024-05-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='plan',
        ),
    ]
