# Generated by Django 4.2.13 on 2024-05-16 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking_project_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Day',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Time',
        ),
        migrations.AddField(
            model_name='booking',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
