# Generated by Django 4.2.11 on 2024-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_booking_delete_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Company',
            field=models.CharField(default='GEG Company', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='plan',
            field=models.ImageField(default='plan.jpg', upload_to='plan/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Email',
            field=models.EmailField(default='timothy@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Mode',
            field=models.TextField(default='Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Phone',
            field=models.IntegerField(default='09324142132', max_length=11),
        ),
    ]
