# Generated by Django 4.2.13 on 2024-05-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_booking_day_remove_booking_time_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateTimeField(default='2022-01-01'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Phone',
            field=models.CharField(default=' ', max_length=11),
        ),
    ]
