# Generated by Django 4.2.11 on 2024-05-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_booking_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='project/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='service/')),
            ],
        ),
    ]
