# Generated by Django 4.2.13 on 2024-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_booking_date_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Phone',
            field=models.CharField(default='09776918809', max_length=11),
        ),
    ]
