# Generated by Django 4.2.11 on 2024-05-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_project_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Image',
        ),
        migrations.AddField(
            model_name='project',
            name='MainImage',
            field=models.ImageField(default='frontend/src/assets/se-dummy-images/dummy-pic-4-abt-us.jpeg', upload_to='project/<django.db.models.fields.CharField>_MainImage'),
        ),
        migrations.AddField(
            model_name='project',
            name='SubImage',
            field=models.ImageField(default='frontend/src/assets/se-dummy-images/dummy-pic-4-abt-us.jpeg', upload_to='project/<django.db.models.fields.CharField>/subimages'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Description',
            field=models.TextField(default='This is a Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Image',
            field=models.ImageField(default='frontend/src/assets/se-dummy-images/dummy-pic-4-abt-us.jpeg', upload_to='service/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Title',
            field=models.CharField(default='Service 1', max_length=50),
        ),
    ]
